### ISSUE TITLE
load_modelb报错,ValueError: You are trying to load a weight file containing 3 layers into a model with 0 layers.

### ISSUE THREAD

**Issue by d4zzz** [SparkSharly/DL_for_xss#2]
* 在train()中保存模型
model.save(model_dir)
test()中进行调用时会报错，
model=load_model(model_dir)

---
Traceback (most recent call last):
  File ".\MLP.py", line 123, in <module>
    test(model_dir,test_generator,test_size,input_num,dims_num,batch_size)
  File ".\MLP.py", line 49, in test
    model=load_model(model_dir)
  File "D:\Python36\lib\site-packages\keras\engine\saving.py", line 263, in load_model
    load_weights_from_hdf5_group(f['model_weights'], model.layers)
  File "D:\Python36\lib\site-packages\keras\engine\saving.py", line 900, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
**ValueError: You are trying to load a weight file containing 3 layers into a model with 0 layers.**

**Comment by cllx** [comment]
请问你这个问题解决了吗 我也有这个问题

**Comment by d4zzz** [comment]
* 在train中按下面方法保存权重

`model.save_weights('test.h5')`

* 在test中重新读取权重
```
    inputs=InputLayer(input_shape=(input_num,dims_num),batch_size=batch_size)
    layer1=Dense(100,activation="relu")
    layer2=Dense(20,activation="relu")
    flatten=Flatten()
    layer3=Dense(2,activation="softmax",name="Output")
    model=Sequential()
    model.add(inputs)
    model.add(layer1)
    model.add(Dropout(0.5))
    model.add(layer2)
    model.add(Dropout(0.5))
    model.add(flatten)
    model.add(layer3)
    model.load_weights('test.h5',by_name=True)
    json_string = model.to_json()
    model = model_from_json(json_string)
```

**Comment by cllx** [comment]
我是把keras版本调回2.1.0运行就没问题了

**Comment by d4zzz** [comment]
> 我是把keras版本调回2.1.0运行就没问题了

这样也可以解决

怎么解决model.predict的调用问题呢，输入单条XSS字符串的数据与InputLayer的大小不相同，根本到不了一个batch那么大

**Comment by cllx** [comment]
我也不是很清楚这个 我在想可不可以按照这里面的分词处理方法把XSS payload进行同样的分词处理成向量 然后用train里的那种方式形成一个test数据（我也是一个初学者 这方面不是很了解）

**Comment by cllx** [comment]
你有这个问题吗 If printing histograms, validation_data must be provided, and cannot be a generator
我想让它printing histograms但又不能报错 不知道要怎么做

**Comment by d4zzz** [comment]
> 你有这个问题吗 If printing histograms, validation_data must be provided, and cannot be a generator
> 我想让它printing histograms但又不能报错 不知道要怎么做

应该是要对model.fit的参数validation_data 形如(x,y)和validation_split设置

**Comment by d4zzz** [comment]
> 我也不是很清楚这个 我在想可不可以按照这里面的分词处理方法把XSS payload进行同样的分词处理成向量 然后用train里的那种方式形成一个test数据（我也是一个初学者 这方面不是很了解）

这样有可能对输入的数据扩展维度之后变稀疏了，特征就不明显了
